# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2da814413d0e41b4ad6dd3d6f5e6905b587a43d33638a4a01dbe768cb1af16fc25bd89c7fa790440fd72ae64e4955d4604d3ba2253ba233879533c0086d07db8

test:
  secret_key_base: f817ac5828fe6d1064df1e45ae3cba7bc6f6966e869cbc5def6e539217fc0c5e235299c7dedd98350f23284a3727fae72d254b5c13747fbfc73d48ae15928c22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
